import Layout from '@/Components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import AnimatedText from '@/Components/AnimatedText'
import Link from 'next/link'
import { CircularText, LinkArrow, ResumeIcon } from '@/Components/Icons'
import HireMe from '@/Components/HireMe'
import lightBulb  from "../../public/images/svgs/miscellaneous_icons_1.svg"
import profilePic from "../../public/images/profile/jasperlee.png"

// Home Page
export default function Home() {
  return (
    <>
      <Head>
        <title>Jasper Lee</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <main className=' flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0'>
          <div className="flex items-start justify-center w-full">

            {/* Home Page Image */}
            {/* <div className='w-full mx-auto'>
              <Image
                src={profilePic}
                alt="JasperLee"
                className='w-full h-auto'
              />
            </div> */}

            {/* Division for Self Introduction Section */}
            <div className=' w-1/2 flex flex-col items-center self-center'>

              {/* Home Page Slogan */}
              <AnimatedText text="Discovering and Unlocking the Power of Data" 
                className='!text-8xl !text-medium mb-10'
              />

              <p className='my-4 text-base font-mont mb-2'>
                As an aspiring data scientist, I am passionate about using the power of data to uncover insights and drive innovation. 
                
                Dive into my latest projects, demonstrating my proficiency in data analysis, machine learning, and Python. 
                
                Explore how I transform raw data into actionable intelligence for everyday convenience.
              </p>

              <div className='flex items-center self-center mt-2'>
                {/* Resume Button */}
                <Link href="/Resume_ywl.pdf"
                target={"_blank"}
                className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent  hover:border-dark
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light '
                download={false}
                >
                  Resume <ResumeIcon className={"w-6 ml-1"}/>
                </Link>

                {/* Contact Button */}
                <Link href="mailto:yaoweilee96@gmail.com" 
                target={'_blank'}
                className='ml-4 text-lg font-medium capitalize text-dark hover:underline
                dark:text-light'                
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe/>
        <div className='absolute right-8 bottom-8 inline-block w-24'>
          <Image src={lightBulb} alt="JasperLee" className='w-full h-auto'/>
        </div>
      </main>
    </>
  )
}
